name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Build
      run: |
        yarn install
        yarn exec gulp
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: fotografie.timon-may.de
  
  archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Copy Quellen.txt into the sources directory
      run: cp Quellen.txt src/
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sources
        path: src/
